/**
 * Seed data for the Finance Dashboard.
 *
 * Provides realistic sample transactions spanning multiple months
 * to demonstrate charting, filtering, and insights features.
 * In a production app, this would come from an API/database.
 */

import { Transaction } from '@/types/finance';

export const seedTransactions: Transaction[] = [
  // January 2024
  {
    id: '1',
    date: '2024-01-05',
    amount: 5500,
    category: 'Salary',
    type: 'income',
    description: 'Monthly salary',
  },
  {
    id: '2',
    date: '2024-01-08',
    amount: 85,
    category: 'Food & Dining',
    type: 'expense',
    description: 'Weekly groceries',
  },
  {
    id: '3',
    date: '2024-01-12',
    amount: 150,
    category: 'Bills & Utilities',
    type: 'expense',
    description: 'Electricity bill',
  },
  {
    id: '4',
    date: '2024-01-15',
    amount: 800,
    category: 'Freelance',
    type: 'income',
    description: 'Freelance web project',
  },
  {
    id: '5',
    date: '2024-01-18',
    amount: 45,
    category: 'Transportation',
    type: 'expense',
    description: 'Gas refill',
  },
  {
    id: '6',
    date: '2024-01-22',
    amount: 120,
    category: 'Shopping',
    type: 'expense',
    description: 'New shoes',
  },
  {
    id: '7',
    date: '2024-01-25',
    amount: 35,
    category: 'Entertainment',
    type: 'expense',
    description: 'Movie night',
  },

  // February 2024
  {
    id: '8',
    date: '2024-02-05',
    amount: 5500,
    category: 'Salary',
    type: 'income',
    description: 'Monthly salary',
  },
  {
    id: '9',
    date: '2024-02-10',
    amount: 200,
    category: 'Healthcare',
    type: 'expense',
    description: 'Dental checkup',
  },
  {
    id: '10',
    date: '2024-02-14',
    amount: 95,
    category: 'Food & Dining',
    type: 'expense',
    description: 'Valentine dinner',
  },
  {
    id: '11',
    date: '2024-02-18',
    amount: 1200,
    category: 'Investments',
    type: 'income',
    description: 'Stock dividends',
  },
  {
    id: '12',
    date: '2024-02-20',
    amount: 160,
    category: 'Bills & Utilities',
    type: 'expense',
    description: 'Internet + phone bill',
  },
  {
    id: '13',
    date: '2024-02-25',
    amount: 350,
    category: 'Education',
    type: 'expense',
    description: 'Online course subscription',
  },

  // March 2024
  {
    id: '14',
    date: '2024-03-05',
    amount: 5500,
    category: 'Salary',
    type: 'income',
    description: 'Monthly salary',
  },
  {
    id: '15',
    date: '2024-03-08',
    amount: 75,
    category: 'Food & Dining',
    type: 'expense',
    description: 'Weekly groceries',
  },
  {
    id: '16',
    date: '2024-03-12',
    amount: 500,
    category: 'Travel',
    type: 'expense',
    description: 'Weekend getaway hotel',
  },
  {
    id: '17',
    date: '2024-03-15',
    amount: 1500,
    category: 'Freelance',
    type: 'income',
    description: 'UI/UX design project',
  },
  {
    id: '18',
    date: '2024-03-20',
    amount: 60,
    category: 'Transportation',
    type: 'expense',
    description: 'Monthly transit pass',
  },
  {
    id: '19',
    date: '2024-03-25',
    amount: 140,
    category: 'Shopping',
    type: 'expense',
    description: 'Spring wardrobe update',
  },
  {
    id: '20',
    date: '2024-03-28',
    amount: 155,
    category: 'Bills & Utilities',
    type: 'expense',
    description: 'Gas + water bills',
  },

  // April 2024
  {
    id: '21',
    date: '2024-04-05',
    amount: 5700,
    category: 'Salary',
    type: 'income',
    description: 'Monthly salary (raise)',
  },
  {
    id: '22',
    date: '2024-04-10',
    amount: 90,
    category: 'Food & Dining',
    type: 'expense',
    description: 'Family dinner out',
  },
  {
    id: '23',
    date: '2024-04-14',
    amount: 250,
    category: 'Healthcare',
    type: 'expense',
    description: 'Annual health checkup',
  },
  {
    id: '24',
    date: '2024-04-18',
    amount: 80,
    category: 'Entertainment',
    type: 'expense',
    description: 'Concert tickets',
  },
  {
    id: '25',
    date: '2024-04-22',
    amount: 600,
    category: 'Investments',
    type: 'income',
    description: 'Mutual fund returns',
  },
  {
    id: '26',
    date: '2024-04-25',
    amount: 170,
    category: 'Bills & Utilities',
    type: 'expense',
    description: 'Electricity + internet',
  },
  {
    id: '27',
    date: '2024-04-28',
    amount: 45,
    category: 'Transportation',
    type: 'expense',
    description: 'Uber rides',
  },

  // May 2024
  {
    id: '28',
    date: '2024-05-05',
    amount: 5700,
    category: 'Salary',
    type: 'income',
    description: 'Monthly salary',
  },
  {
    id: '29',
    date: '2024-05-10',
    amount: 1800,
    category: 'Travel',
    type: 'expense',
    description: 'Summer vacation flight',
  },
  {
    id: '30',
    date: '2024-05-15',
    amount: 110,
    category: 'Food & Dining',
    type: 'expense',
    description: 'Birthday celebration',
  },
  {
    id: '31',
    date: '2024-05-18',
    amount: 2000,
    category: 'Freelance',
    type: 'income',
    description: 'Mobile app project',
  },
  {
    id: '32',
    date: '2024-05-22',
    amount: 300,
    category: 'Shopping',
    type: 'expense',
    description: 'Electronics purchase',
  },
  {
    id: '33',
    date: '2024-05-25',
    amount: 165,
    category: 'Bills & Utilities',
    type: 'expense',
    description: 'Monthly utilities',
  },
  {
    id: '34',
    date: '2024-05-28',
    amount: 400,
    category: 'Education',
    type: 'expense',
    description: 'Workshop registration',
  },
];
